[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@forge-std/=lib/forge-std/src/",
    "@level0/=src/level0/",
    "@level1/=src/level1/",
    "@huff/=lib/foundry-huff/src/",
    "@math/=lib/openzeppelin-contracts/contracts/utils/math/",
    "@arrays/=lib/openzeppelin-contracts/contracts/utils/",
    "@level2/=src/level2/",
    "@level3/=src/level3/",
    "@level4/=src/level4/",
    "@level5/=src/level5/",
]
ffi = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia_api = { key = "${ETHERSCAN_API_KEY}" }
