[profile.default]
src = "src"
out = "out/poc-foundry-upgrades"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "out/poc-foundry-upgrades" }]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
